version: '3.8'
services:  

  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: postgres1234
    volumes:
      - /var/lib/postgresql/data      
    networks:
      - test
    ports:
      - "5432:5432"

  app:
    build:
      dockerfile: Dockerfile
    container_name: api 
    restart: on-failure     
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - test

networks:
  test:
    name: test